import '../../core/constants/angular_size_class.dart';
import '../../core/constants/imaging_difficulty.dart';
import '../../core/constants/object_type.dart';
import '../../core/constants/surface_brightness_class.dart';
import '../../data/models/object_imaging_profile.dart';

/// Default imaging profiles keyed by [ObjectType].
abstract final class ObjectImagingProfileDefaults {
  static ObjectImagingProfile forType(ObjectType type) {
    return _defaults[type] ?? _defaults[ObjectType.other]!;
  }

  static const _defaults = <ObjectType, ObjectImagingProfile>{
    ObjectType.galaxy: ObjectImagingProfile(
      objectType: ObjectType.galaxy,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 37,
      minimumRecommendedBortle: 7,
      recommendedBortle: 8,
      supportsNarrowband: false,
      recommendedFilters: ['L', 'R', 'G', 'B'],
    ),
    ObjectType.galaxyGroup: ObjectImagingProfile(
      objectType: ObjectType.galaxyGroup,
      imagingDifficulty: ImagingDifficulty.hard,
      surfaceBrightnessClass: SurfaceBrightnessClass.dim,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 90,
      minimumRecommendedBortle: 6,
      recommendedBortle: 3,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.emissionNebula: ObjectImagingProfile(
      objectType: ObjectType.emissionNebula,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.medium,
      baseExposureMinutes: 30,
      minimumRecommendedBortle: 9,
      recommendedBortle: 8,
      supportsNarrowband: true,
      recommendedFilters: ['Ha', 'OIII', 'SII'],
    ),
    ObjectType.reflectionNebula: ObjectImagingProfile(
      objectType: ObjectType.reflectionNebula,
      imagingDifficulty: ImagingDifficulty.normal,
      surfaceBrightnessClass: SurfaceBrightnessClass.dim,
      angularSizeClass: AngularSizeClass.medium,
      baseExposureMinutes: 60,
      minimumRecommendedBortle: 5,
      recommendedBortle: 3,
      supportsNarrowband: false,
      recommendedFilters: ['L', 'R', 'G', 'B'],
    ),
    ObjectType.darkNebula: ObjectImagingProfile(
      objectType: ObjectType.darkNebula,
      imagingDifficulty: ImagingDifficulty.veryHard,
      surfaceBrightnessClass: SurfaceBrightnessClass.extremeDim,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 120,
      minimumRecommendedBortle: 4,
      recommendedBortle: 2,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.planetaryNebula: ObjectImagingProfile(
      objectType: ObjectType.planetaryNebula,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.normal,
      angularSizeClass: AngularSizeClass.small,
      baseExposureMinutes: 45,
      minimumRecommendedBortle: 7,
      recommendedBortle: 7,
      supportsNarrowband: true,
      recommendedFilters: ['OIII', 'Ha'],
    ),
    ObjectType.openCluster: ObjectImagingProfile(
      objectType: ObjectType.openCluster,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.medium,
      baseExposureMinutes: 30,
      minimumRecommendedBortle: 9,
      recommendedBortle: 8,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.globularCluster: ObjectImagingProfile(
      objectType: ObjectType.globularCluster,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.normal,
      angularSizeClass: AngularSizeClass.small,
      baseExposureMinutes: 45,
      minimumRecommendedBortle: 8,
      recommendedBortle: 8,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.supernovaRemnant: ObjectImagingProfile(
      objectType: ObjectType.supernovaRemnant,
      imagingDifficulty: ImagingDifficulty.hard,
      surfaceBrightnessClass: SurfaceBrightnessClass.dim,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 90,
      minimumRecommendedBortle: 6,
      recommendedBortle: 7,
      supportsNarrowband: true,
      recommendedFilters: ['Ha', 'OIII'],
    ),
    ObjectType.complexNebula: ObjectImagingProfile(
      objectType: ObjectType.complexNebula,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 50,
      minimumRecommendedBortle: 9,
      recommendedBortle: 8,
      supportsNarrowband: true,
      recommendedFilters: ['Ha', 'OIII'],
    ),
    ObjectType.nebulaWithCluster: ObjectImagingProfile(
      objectType: ObjectType.nebulaWithCluster,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.medium,
      baseExposureMinutes: 50,
      minimumRecommendedBortle: 8,
      recommendedBortle: 8,
      supportsNarrowband: true,
      recommendedFilters: ['Ha'],
    ),
    ObjectType.starCloud: ObjectImagingProfile(
      objectType: ObjectType.starCloud,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.bright,
      angularSizeClass: AngularSizeClass.veryLarge,
      baseExposureMinutes: 30,
      minimumRecommendedBortle: 7,
      recommendedBortle: 4,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.milkyWay: ObjectImagingProfile(
      objectType: ObjectType.milkyWay,
      imagingDifficulty: ImagingDifficulty.easy,
      surfaceBrightnessClass: SurfaceBrightnessClass.normal,
      angularSizeClass: AngularSizeClass.veryLarge,
      baseExposureMinutes: 45,
      minimumRecommendedBortle: 6,
      recommendedBortle: 3,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.doubleStar: ObjectImagingProfile(
      objectType: ObjectType.doubleStar,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.veryBright,
      angularSizeClass: AngularSizeClass.verySmall,
      baseExposureMinutes: 10,
      minimumRecommendedBortle: 9,
      recommendedBortle: 6,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.star: ObjectImagingProfile(
      objectType: ObjectType.star,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.veryBright,
      angularSizeClass: AngularSizeClass.verySmall,
      baseExposureMinutes: 10,
      minimumRecommendedBortle: 9,
      recommendedBortle: 6,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.planet: ObjectImagingProfile(
      objectType: ObjectType.planet,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.veryBright,
      angularSizeClass: AngularSizeClass.verySmall,
      baseExposureMinutes: 5,
      minimumRecommendedBortle: 9,
      recommendedBortle: 8,
      supportsNarrowband: false,
      recommendedFilters: ['L', 'R', 'G', 'B'],
    ),
    ObjectType.moon: ObjectImagingProfile(
      objectType: ObjectType.moon,
      imagingDifficulty: ImagingDifficulty.veryEasy,
      surfaceBrightnessClass: SurfaceBrightnessClass.veryBright,
      angularSizeClass: AngularSizeClass.large,
      baseExposureMinutes: 5,
      minimumRecommendedBortle: 9,
      recommendedBortle: 8,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.dwarfPlanet: ObjectImagingProfile(
      objectType: ObjectType.dwarfPlanet,
      imagingDifficulty: ImagingDifficulty.hard,
      surfaceBrightnessClass: SurfaceBrightnessClass.dim,
      angularSizeClass: AngularSizeClass.verySmall,
      baseExposureMinutes: 60,
      minimumRecommendedBortle: 5,
      recommendedBortle: 3,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
    ObjectType.other: ObjectImagingProfile(
      objectType: ObjectType.other,
      imagingDifficulty: ImagingDifficulty.normal,
      surfaceBrightnessClass: SurfaceBrightnessClass.normal,
      angularSizeClass: AngularSizeClass.medium,
      baseExposureMinutes: 60,
      minimumRecommendedBortle: 6,
      recommendedBortle: 4,
      supportsNarrowband: false,
      recommendedFilters: ['L'],
    ),
  };
}
